apiVersion: k3d.io/v1alpha5 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
#metadata:
#  name: default # name that you want to give to your cluster (will still be prefixed with `k3d-`)
servers: 1 # same as `--servers 1`
agents: 0 # same as `--agents 2`
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  host: "localhost" # important for the `server` setting in the kubeconfig
  #hostIP: {{ DOCKER_HOST_IP }} # where the Kubernetes API will be listening on
  hostPort: "6443" # where the Kubernetes API listening port will be mapped to on your host system
image: rancher/k3s:v1.31.4-k3s1 # same as `--image rancher/k3s:v1.31.4-k3s1`
token: superSecretToken # same as `--token superSecretToken`
ports:
  - port: 22:22 # same as `--port '22:22@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 80:80 # same as `--port '6780:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443 # same as `--port '6743:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 6780:80 # same as `--port '6780:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 6743:443 # same as `--port '6743:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8000:8000 # same as `--port '8000:8000@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8443:8443 # same as `--port '8443:8443@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8001:8001 # same as `--port '8001:8001@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8002:8002 # same as `--port '8002:8002@loadbalancer'`
    nodeFilters:
      - loadbalancer
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
    timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
    disableLoadbalancer: false # same as `--no-lb`
    disableImageVolume: false # same as `--no-image-volume`
    disableRollback: false # same as `--no-Rollback`
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
    switchCurrentContext: true # also set current-context to the new cluster's context; same as `--kubeconfig-switch-context` (default: true)
